# Generated by Django 3.1.3 on 2020-11-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(upload_to='portfolio_app/images'),
        ),
    ]
